using System;
using System.Collections.Generic;

namespace DataHelper.Entity.WSEntities
{
    public partial class SafeProductcount
    {
        public int Id { get; set; }
        public string SfName1 { get; set; }
        public string SfName2 { get; set; }
        public string SfName3 { get; set; }
        public string SfName4 { get; set; }
        public string SfName5 { get; set; }
        public string SfName6 { get; set; }
        public string SfName7 { get; set; }
        public string SfName8 { get; set; }
        public string SfName9 { get; set; }
        public string SfName10 { get; set; }
        public string SfName11 { get; set; }
        public string SfName12 { get; set; }
        public string SfName13 { get; set; }
        public string SfName14 { get; set; }
        public string SfName15 { get; set; }
        public string SfName16 { get; set; }
        public string SfName17 { get; set; }
        public string SfName18 { get; set; }
        public string SfName19 { get; set; }
        public string SfName20 { get; set; }
        public string SfName21 { get; set; }
        public string SfName22 { get; set; }
        public string SfName23 { get; set; }
        public string SfName24 { get; set; }
        public string SfName25 { get; set; }
        public string SfName26 { get; set; }
        public string SfName27 { get; set; }
        public string SfName28 { get; set; }
        public string SfName29 { get; set; }
        public string SfName30 { get; set; }
        public string SfName31 { get; set; }
        public string SfName32 { get; set; }
        public string SfName33 { get; set; }
        public string SfName34 { get; set; }
        public string SfName35 { get; set; }
        public string SfName36 { get; set; }
        public string SfName37 { get; set; }
        public string SfName38 { get; set; }
        public string SfName39 { get; set; }
        public string SfName40 { get; set; }
        public string SfName41 { get; set; }
        public string SfName42 { get; set; }
        public string SfName43 { get; set; }
        public string SfName44 { get; set; }
        public string SfName45 { get; set; }
        public string SfName46 { get; set; }
        public string SfName47 { get; set; }
        public string SfName48 { get; set; }
        public string SfName49 { get; set; }
        public string SfName50 { get; set; }
        public string SfName51 { get; set; }
        public string SfName52 { get; set; }
        public string SfName53 { get; set; }
        public string SfName54 { get; set; }
        public string SfName55 { get; set; }
        public string SfName56 { get; set; }
        public string SfName57 { get; set; }
        public string SfName58 { get; set; }
        public string SfName59 { get; set; }
        public string SfName60 { get; set; }
        public string SfName61 { get; set; }
        public string SfName62 { get; set; }
        public string SfName63 { get; set; }
        public string SfName64 { get; set; }
        public string SfName65 { get; set; }
        public string SfName66 { get; set; }
        public string SfName67 { get; set; }
        public string SfName68 { get; set; }
        public string SfName69 { get; set; }
        public string SfName70 { get; set; }
        public string SfName71 { get; set; }
        public string SfName72 { get; set; }
        public string SfName73 { get; set; }
        public string SfName74 { get; set; }
        public string SfName75 { get; set; }
        public string SfName76 { get; set; }
        public string SfName77 { get; set; }
        public string SfName78 { get; set; }
        public string SfName79 { get; set; }
        public string SfName80 { get; set; }
        public string SfName81 { get; set; }
        public string SfName82 { get; set; }
        public string SfName83 { get; set; }
        public string SfName84 { get; set; }
        public string SfName85 { get; set; }
        public string SfName86 { get; set; }
        public string SfName87 { get; set; }
        public string SfName88 { get; set; }
        public string SfName89 { get; set; }
        public string SfName90 { get; set; }
        public string SfName91 { get; set; }
        public string SfName92 { get; set; }
        public string SfName93 { get; set; }
        public string SfName94 { get; set; }
        public string SfName95 { get; set; }
        public string SfName96 { get; set; }
        public string SfName97 { get; set; }
        public string SfName98 { get; set; }
        public string SfName99 { get; set; }
        public string SfName100 { get; set; }
        public int? DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string Year { get; set; }
        public int? Quarter { get; set; }
        public DateTime? CreateTime { get; set; }
        public int? IsCount { get; set; }
        public int? Submitcount { get; set; }
        public int? Checkcount { get; set; }
        public int? Totalcount { get; set; }
        public int? IsVisible { get; set; }
        public int? CurrentStep { get; set; }
        public int? FlowId { get; set; }
        public int? Status { get; set; }
    }
}
