using System;
using System.Collections.Generic;

namespace DataHelper.Entity.WSEntities
{
    public partial class SafeProduct
    {
        public int Id { get; set; }
        public string SfName1 { get; set; }
        public string SfName2 { get; set; }
        public string SfName3 { get; set; }
        public string SfName4 { get; set; }
        public string SfName5 { get; set; }
        public string SfName6 { get; set; }
        public string SfName7 { get; set; }
        public string SfName8 { get; set; }
        public string SfName9 { get; set; }
        public string SfName10 { get; set; }
        public string SfName11 { get; set; }
        public string SfName12 { get; set; }
        public string SfName13 { get; set; }
        public string SfName14 { get; set; }
        public string SfName15 { get; set; }
        public string SfName16 { get; set; }
        public int? SfName17 { get; set; }
        public int? SfName18 { get; set; }
        public int? SfName19 { get; set; }
        public int? SfName20 { get; set; }
        public int? SfName21 { get; set; }
        public int? SfName22 { get; set; }
        public int? SfName23 { get; set; }
        public int? SfName24 { get; set; }
        public int? SfName25 { get; set; }
        public int? SfName26 { get; set; }
        public int? SfName27 { get; set; }
        public int? SfName28 { get; set; }
        public int? SfName29 { get; set; }
        public int? SfName30 { get; set; }
        public int? SfName31 { get; set; }
        public int? SfName32 { get; set; }
        public int? SfName33 { get; set; }
        public int? SfName34 { get; set; }
        public int? SfName35 { get; set; }
        public int? SfName36 { get; set; }
        public int? SfName37 { get; set; }
        public int? SfName38 { get; set; }
        public int? SfName39 { get; set; }
        public int? SfName40 { get; set; }
        public int? SfName41 { get; set; }
        public int? SfName42 { get; set; }
        public int? SfName43 { get; set; }
        public int? SfName44 { get; set; }
        public int? SfName45 { get; set; }
        public string SfName46 { get; set; }
        public string SfName47 { get; set; }
        public string SfName48 { get; set; }
        public string SfName49 { get; set; }
        public string SfName50 { get; set; }
        public string SfName51 { get; set; }
        public string SfName52 { get; set; }
        public string SfName53 { get; set; }
        public string SfName54 { get; set; }
        public string SfName55 { get; set; }
        public string SfName56 { get; set; }
        public string SfName57 { get; set; }
        public string SfName58 { get; set; }
        public string SfName59 { get; set; }
        public string SfName60 { get; set; }
        public string SfName61 { get; set; }
        public string SfName62 { get; set; }
        public string SfName63 { get; set; }
        public string SfName64 { get; set; }
        public string SfName65 { get; set; }
        public string SfName66 { get; set; }
        public string SfName67 { get; set; }
        public string SfName68 { get; set; }
        public string SfName69 { get; set; }
        public string SfName70 { get; set; }
        public string SfName71 { get; set; }
        public string SfName72 { get; set; }
        public string SfName73 { get; set; }
        public string SfName74 { get; set; }
        public string SfName75 { get; set; }
        public string SfName76 { get; set; }
        public string SfName77 { get; set; }
        public string SfName78 { get; set; }
        public string SfName79 { get; set; }
        public string SfName80 { get; set; }
        public string SfName81 { get; set; }
        public string SfName82 { get; set; }
        public string SfName83 { get; set; }
        public string SfName84 { get; set; }
        public string SfName85 { get; set; }
        public string SfName86 { get; set; }
        public string SfName87 { get; set; }
        public string SfName88 { get; set; }
        public string SfName89 { get; set; }
        public string SfName90 { get; set; }
        public string SfName91 { get; set; }
        public string SfName92 { get; set; }
        public string SfName93 { get; set; }
        public string SfName94 { get; set; }
        public string SfName95 { get; set; }
        public string SfName96 { get; set; }
        public string SfName97 { get; set; }
        public string SfName98 { get; set; }
        public string SfName99 { get; set; }
        public string SfName100 { get; set; }
        public string DepartmentName { get; set; }
        public int? DepartmentId { get; set; }
        public string Year { get; set; }
        public int? Quarter { get; set; }
        public DateTime? CreateTime { get; set; }
        public int? IsCount { get; set; }
        public int? IsVisible { get; set; }
        public string CreateName { get; set; }
        public int? CreateUid { get; set; }
        public int? CurrentStep { get; set; }
        public int? FlowId { get; set; }
        public int? Status { get; set; }
        public string ProvinceName { get; set; }
        public int? ProvinceId { get; set; }
    }
}
