using System;
using System.Collections.Generic;

namespace DataHelper.Entity.WSEntities
{
    public partial class SafeQuestion
    {
        public int Id { get; set; }
        public string SqName1 { get; set; }
        public int? SqName2 { get; set; }
        public int? SqName3 { get; set; }
        public int? SqName4 { get; set; }
        public int? SqName5 { get; set; }
        public int? SqName6 { get; set; }
        public int? SqName7 { get; set; }
        public int? SqName8 { get; set; }
        public int? SqName9 { get; set; }
        public int? SqName10 { get; set; }
        public int? SqName11 { get; set; }
        public int? SqName12 { get; set; }
        public int? SqName13 { get; set; }
        public int? SqName14 { get; set; }
        public int? SqName15 { get; set; }
        public int? SqName16 { get; set; }
        public int? SqName17 { get; set; }
        public int? SqName18 { get; set; }
        public int? SqName19 { get; set; }
        public int? SqName20 { get; set; }
        public int? SqName21 { get; set; }
        public int? SqName22 { get; set; }
        public int? SqName23 { get; set; }
        public int? SqName24 { get; set; }
        public int? SqName25 { get; set; }
        public int? SqName26 { get; set; }
        public int? SqName27 { get; set; }
        public int? SqName28 { get; set; }
        public int? SqName29 { get; set; }
        public int? SqName30 { get; set; }
        public int? SqName31 { get; set; }
        public int? SqName32 { get; set; }
        public int? SqName33 { get; set; }
        public int? SqName34 { get; set; }
        public int? SqName35 { get; set; }
        public int? SqName36 { get; set; }
        public int? SqName37 { get; set; }
        public int? SqName38 { get; set; }
        public int? SqName39 { get; set; }
        public int? SqName40 { get; set; }
        public int? SqName41 { get; set; }
        public int? SqName42 { get; set; }
        public int? SqName43 { get; set; }
        public int? SqName44 { get; set; }
        public int? SqName45 { get; set; }
        public int? SqName46 { get; set; }
        public int? SqName47 { get; set; }
        public int? SqName48 { get; set; }
        public int? SqName49 { get; set; }
        public int? SqName50 { get; set; }
        public int? SqName51 { get; set; }
        public int? SqName52 { get; set; }
        public int? SqName53 { get; set; }
        public int? SqName54 { get; set; }
        public int? SqName55 { get; set; }
        public int? SqName56 { get; set; }
        public int? SqName57 { get; set; }
        public int? SqName58 { get; set; }
        public int? SqName59 { get; set; }
        public int? SqName60 { get; set; }
        public int? SqName61 { get; set; }
        public int? SqName62 { get; set; }
        public int? SqName63 { get; set; }
        public int? SqName64 { get; set; }
        public int? SqName65 { get; set; }
        public int? SqName66 { get; set; }
        public int? SqName67 { get; set; }
        public int? SqName68 { get; set; }
        public int? SqName69 { get; set; }
        public int? SqName70 { get; set; }
        public int? SqName71 { get; set; }
        public int? SqName72 { get; set; }
        public int? SqName73 { get; set; }
        public int? SqName74 { get; set; }
        public int? SqName75 { get; set; }
        public int? SqName76 { get; set; }
        public int? SqName77 { get; set; }
        public int? SqName78 { get; set; }
        public int? SqName79 { get; set; }
        public int? SqName80 { get; set; }
        public int? SqName81 { get; set; }
        public int? SqName82 { get; set; }
        public int? SqName83 { get; set; }
        public int? SqName84 { get; set; }
        public int? SqName85 { get; set; }
        public int? SqName86 { get; set; }
        public int? SqName87 { get; set; }
        public int? SqName88 { get; set; }
        public int? SqName89 { get; set; }
        public int? SqName90 { get; set; }
        public int? SqName91 { get; set; }
        public int? SqName92 { get; set; }
        public int? SqName93 { get; set; }
        public int? SqName94 { get; set; }
        public int? SqName95 { get; set; }
        public int? SqName96 { get; set; }
        public int? SqName97 { get; set; }
        public int? SqName98 { get; set; }
        public int? SqName99 { get; set; }
        public int? SqName100 { get; set; }
        public int? DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public int? Quarter { get; set; }
        public string Year { get; set; }
        public DateTime? CreateTime { get; set; }
        public int? IsCheck { get; set; }
        public int? IsCount { get; set; }
        public int? IsVisible { get; set; }
        public string CreateName { get; set; }
        public int? CreateUid { get; set; }
        public int? CurrentStep { get; set; }
        public int? FlowId { get; set; }
        public int? Status { get; set; }
        public int? ProvinceId { get; set; }
        public string ProvinceName { get; set; }
    }
}
