using System;
using System.Collections.Generic;

namespace DataHelper.Entity.WSEntities
{
    public partial class SafeQuestioncount
    {
        public int Id { get; set; }
        public string SqName1 { get; set; }
        public string SqName2 { get; set; }
        public string SqName3 { get; set; }
        public string SqName4 { get; set; }
        public string SqName5 { get; set; }
        public string SqName6 { get; set; }
        public string SqName7 { get; set; }
        public string SqName8 { get; set; }
        public string SqName9 { get; set; }
        public string SqName10 { get; set; }
        public string SqName11 { get; set; }
        public string SqName12 { get; set; }
        public string SqName13 { get; set; }
        public string SqName14 { get; set; }
        public string SqName15 { get; set; }
        public string SqName16 { get; set; }
        public string SqName17 { get; set; }
        public string SqName18 { get; set; }
        public string SqName19 { get; set; }
        public string SqName20 { get; set; }
        public string SqName21 { get; set; }
        public string SqName22 { get; set; }
        public string SqName23 { get; set; }
        public string SqName24 { get; set; }
        public string SqName25 { get; set; }
        public string SqName26 { get; set; }
        public string SqName27 { get; set; }
        public string SqName28 { get; set; }
        public string SqName29 { get; set; }
        public string SqName30 { get; set; }
        public string SqName31 { get; set; }
        public string SqName32 { get; set; }
        public string SqName33 { get; set; }
        public string SqName34 { get; set; }
        public string SqName35 { get; set; }
        public string SqName36 { get; set; }
        public string SqName37 { get; set; }
        public string SqName38 { get; set; }
        public string SqName39 { get; set; }
        public string SqName40 { get; set; }
        public string SqName41 { get; set; }
        public string SqName42 { get; set; }
        public string SqName43 { get; set; }
        public string SqName44 { get; set; }
        public string SqName45 { get; set; }
        public string SqName46 { get; set; }
        public string SqName47 { get; set; }
        public string SqName48 { get; set; }
        public string SqName49 { get; set; }
        public string SqName50 { get; set; }
        public string SqName51 { get; set; }
        public string SqName52 { get; set; }
        public string SqName53 { get; set; }
        public string SqName54 { get; set; }
        public string SqName55 { get; set; }
        public string SqName56 { get; set; }
        public string SqName57 { get; set; }
        public string SqName58 { get; set; }
        public string SqName59 { get; set; }
        public string SqName60 { get; set; }
        public string SqName61 { get; set; }
        public string SqName62 { get; set; }
        public string SqName63 { get; set; }
        public string SqName64 { get; set; }
        public string SqName65 { get; set; }
        public string SqName66 { get; set; }
        public string SqName67 { get; set; }
        public string SqName68 { get; set; }
        public string SqName69 { get; set; }
        public string SqName70 { get; set; }
        public string SqName71 { get; set; }
        public string SqName72 { get; set; }
        public string SqName73 { get; set; }
        public string SqName74 { get; set; }
        public string SqName75 { get; set; }
        public string SqName76 { get; set; }
        public string SqName77 { get; set; }
        public string SqName78 { get; set; }
        public string SqName79 { get; set; }
        public string SqName80 { get; set; }
        public string SqName81 { get; set; }
        public string SqName82 { get; set; }
        public string SqName83 { get; set; }
        public string SqName84 { get; set; }
        public string SqName85 { get; set; }
        public string SqName86 { get; set; }
        public string SqName87 { get; set; }
        public string SqName88 { get; set; }
        public string SqName89 { get; set; }
        public string SqName90 { get; set; }
        public string SqName91 { get; set; }
        public string SqName92 { get; set; }
        public string SqName93 { get; set; }
        public string SqName94 { get; set; }
        public string SqName95 { get; set; }
        public string SqName96 { get; set; }
        public string SqName97 { get; set; }
        public string SqName98 { get; set; }
        public string SqName99 { get; set; }
        public string SqName100 { get; set; }
        public string DepartmentName { get; set; }
        public int? DepartmentId { get; set; }
        public int? Quarter { get; set; }
        public string Year { get; set; }
        public DateTime? CreateTime { get; set; }
        public int? Submitcount { get; set; }
        public int? Checkcount { get; set; }
        public int? Totalcount { get; set; }
        public int? IsVisible { get; set; }
        public int? CurrentStep { get; set; }
        public int? FlowId { get; set; }
        public int? Status { get; set; }
    }
}
